dist: trusty
language: java
jdk:
- oraclejdk8

script: mvn clean install

after_success:
- mvn clean test jacoco:report coveralls:report

notifications:
  slack: digital-bauhaus:2ZFDhvBSWsjMpEVQitxCzxmY
  email:
    on_success: never
